#define VERSION_BRICKS_MAJOR        1
#define VERSION_BRICKS_MINOR        0 
#define VERSION_BRICKS_REVISION     1
#define VERSION_BRICKS_BUILD        0

#define VERSION_BRICKS_VERSION VERSION_BRICKS_MAJOR,VERSION_BRICKS_MINOR,VERSION_BRICKS_REVISION,VERSION_BRICKS_BUILD
#define VERSION_BRICKS_VERSION_DOT "1.0.1.0"


#define COMPANY_NAME_BRICKS "Pretty Things Flying"
